if ENV['TRAVIS']
  require 'coveralls'
  Coveralls.wear!
else
  require 'simplecov'
  SimpleCov.start
end
# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
require 'gitlab_git'
require File.join(File.dirname(__FILE__), '../support/valid_commit')
require 'pry'

RSpec::Matchers.define :be_valid_commit do
  match do |actual|
    actual != nil
    actual.id == ValidCommit::ID
    actual.message == ValidCommit::MESSAGE
    actual.author_name == ValidCommit::AUTHOR_FULL_NAME
  end
end

SUPPORT_PATH = File.join(File.expand_path(File.dirname(__FILE__)), '../support')
TEST_REPO_PATH = File.join(SUPPORT_PATH, 'gitlabhq.git')
TEST_SUB_REPO_PATH = File.join(SUPPORT_PATH, 'submodules.git')


RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
  config.order = 'random'

  config.before(:all) do
    FileUtils.cd(SUPPORT_PATH) do
      %w(gitlabhq submodules).each do |repo|
        `rm -rf #{repo}.git`
        `tar -xf #{repo}.tar.gz`
        `mv #{repo} #{repo}.git`
      end
    end
  end
end
