if ENV['TRAVIS']
  require 'coveralls'
  Coveralls.wear!
end
# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
require 'gitlab_git'
require File.join(File.dirname(__FILE__), '../support/valid_commit')
require 'pry'

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
  config.order = 'random'

  config.before(:all) do
    support_path = File.join(File.expand_path(File.dirname(__FILE__)), '../support')

    FileUtils.cd(support_path) do
      # Extract the archive
      `rm -rf gitlabhq.git`
      `tar -xf seed_project.tar.gz`
      `mv gitlabhq gitlabhq.git`
    end

    Gitlab::Git::Repository.repos_path = support_path
  end
end
